### PR TITLE
Replacing the gradle java plugin with java-library

### PR DESCRIPTION
**Pull request by lbergelson**
* updating vulnerable dependencies
* replacing use of commons-lang Path with new barclay Path
* reducing dependency scope where possible

### CODE REVIEW

**Review by cmnbroad — COMMENTED** [review]
Seems fine (we also use the old commons Pair class all over the place in GATK).

One request though - can you autogen/add `hashCode `/`equals` methods to `Pair`, since they get used all over the place.

**Review by cmnbroad — APPROVED** [review]

**Comment by lbergelson** [comment]
@cmnbroad One of the nice things about records is they do that for you.  There are implicit equals/hashCode/toString methods that are reasonable and based on the declared fields.

https://docs.oracle.com/en/java/javase/17/language/records.html#GUID-6699E26F-4A9B-4393-A08B-1E47D4B2D263

**Comment by lbergelson** [comment]
Getting rid of the commons pair in the interfaces is maybe a bit silly.  Might as well try to reduce the dependency surface a bit though.

**Comment by cmnbroad** [comment]
Oh yeah - I knew that and completely forgot.

**Pull request merged**
